apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy
  name: my-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-deploy
  type: NodePort
status:
  loadBalancer: {}
